//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitofWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseStudy
    {
        public int id { get; set; }
        public string PageName { get; set; }
        public string title_seo { get; set; }
        public string desc_seo { get; set; }
        public string key_seo { get; set; }
        public string banner_img { get; set; }
        public string Title { get; set; }
        public string Mail_Content { get; set; }
        public string footer { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string Category { get; set; }
    }
}
